# Generated by Django 4.1.2 on 2022-11-11 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('alias', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=8)),
                ('reeup', models.CharField(max_length=15)),
                ('nit', models.CharField(max_length=15)),
                ('cuenta_bancaria', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='ContratoAbstracto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_firma', models.DateField()),
                ('estado_contrato', models.CharField(choices=[('OP', 'OPORTUNIDAD'), ('SOL', 'SOLICITADO'), ('REC', 'RECIBIDO'), ('FIR', 'FIRMADO'), ('CLO', 'CERRADO'), ('CAN', 'CANCELADO')], default='OP', max_length=15)),
                ('nivel_contratacion', models.CharField(choices=[('MUN', 'MUNICIPIO'), ('PRV', 'PROVINCIA'), ('OTR', 'OTRO')], default='MUN', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetallesFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Surtido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoEspecifico',
            fields=[
                ('contratoabstracto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cmi_brigada.contratoabstracto')),
                ('numero', models.CharField(max_length=5)),
            ],
            bases=('cmi_brigada.contratoabstracto',),
        ),
        migrations.CreateModel(
            name='ContratoMarco',
            fields=[
                ('contratoabstracto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cmi_brigada.contratoabstracto')),
                ('cod_contrato', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'contrato marco',
                'verbose_name_plural': 'contratos marco',
            },
            bases=('cmi_brigada.contratoabstracto',),
        ),
    ]
